routes/web.php
<?php

use App\Http\Controllers\Admin\RoleController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ExpressController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\ScaleController;
use App\Http\Controllers\Admin\UnitController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\FarmProductTypeController;
use App\Http\Controllers\Admin\TypeReportController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\LocationController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Customer\CartController;
use App\Http\Controllers\Customer\OrderController;
use App\Http\Controllers\FilterController;
use App\Http\Controllers\Guest\ProductDetailController;
use App\Http\Controllers\Guest\FilterController as GuestFilterController;
use App\Http\Controllers\Guest\ProductShowController;
use App\Http\Controllers\Guest\FarmProductTypeFilterController;
use App\Http\Controllers\Guest\FarmerController;
use App\Http\Controllers\Guest\NewsController;
use App\Http\Controllers\Guest\BlogController;
use App\Http\Controllers\Guest\SearchingController;
use App\Http\Controllers\Admin\SaleController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';


Route::prefix('/')->namespace('Guest')->name('guest.')->group(function () {

    Route::get('/farm-product-type/{product_type_slug}', [FarmProductTypeFilterController::class, 'show'])->name('type');
    Route::get('/product-type', [FarmProductTypeFilterController::class, 'filter'])->name('filter');
    Route::get('/', [ProductShowController::class, 'index'])->name('index');

    Route::prefix('product')->namespace('Product')->name('product.')->group(function () {
        Route::get('/show/{product_slug}', [ProductDetailController::class, 'productDetail'])->name('productdetail');
        Route::get('/farm-product-filter', [GuestFilterController::class, 'index'])->name('index');

        Route::get('/filter', [GuestFilterController::class, 'filter'])->name('filter');
        Route::get('/filter_two', [GuestFilterController::class, 'filter_two'])->name('filter_two');
    });
    Route::prefix('seller')->namespace('Seller')->name('seller.')->group(function () {
        Route::get('/{id}', [FarmerController::class, 'index'])->name('index');
        Route::get('/filter/{id}', [FarmerController::class, 'filter'])->name('filter');
        Route::get('/order-by/{id}', [FarmerController::class, 'farmerOrderBy'])->name('order-by');
    });
    Route::prefix('blogs')->namespace('Blogs')->name('blogs.')->group(function () {
        Route::get('/{id}', [BlogController::class, 'index'])->name('index');
        Route::get('/category/{category_slug}', [BlogController::class, 'categoryPost'])->name('category-post');
        Route::get('/read/{post_slug}', [BlogController::class, 'read'])->name('read');
    });
    Route::prefix('news')->namespace('News')->name('news.')->group(function () {
        Route::get('/', [NewsController::class, 'index'])->name('index');
        Route::get('/category/{category_slug}', [NewsController::class, 'categoryPost'])->name('category-post');
        Route::get('/{post_slug}', [NewsController::class, 'read'])->name('read');
    });
    Route::get('/searching', [SearchingController::class, 'searchProduct'])->name('search');

    Route::get('/search', [SearchingController::class, 'searchPost'])->name('search-post');
});

//Get location
Route::prefix('locations')->namespace('Locations')->name('locations.')->group(function () {
    Route::get('/', [LocationController::class, 'index'])->name('location');
    Route::post('/get-province-by-region', [LocationController::class, 'getProvince'])->name('get-province');
    Route::post('/get-district-by-province', [LocationController::class, 'getDistrict'])->name('get-district');
    Route::post('/get-ward-by-district', [LocationController::class, 'getWard'])->name('get-ward');
});

//User: ADMIN
Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware(['web', 'auth', 'role:admin|farmer'])->group(function () {
    Route::get('/', function () {
        return view('admin.layout');
    })->name('index');

    Route::prefix('sales')->namespace('Sales')->name('sales.')->middleware(['can:statistic'])->group(function () {
        Route::get('/', [SaleController::class, 'index'])->name('index');
    });

    Route::prefix('products')->namespace('Products')->name('products.')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index')->middleware(['can:farm-produce.view']);
        Route::get('/add', [ProductController::class, 'create'])->name('add')->middleware(['can:farm-produce.*']);
        Route::post('/add', [ProductController::class, 'store'])->name('store')->middleware(['can:farm-produce.*']);
        Route::get('/update/{id}', [ProductController::class, 'edit'])->name('edit')->middleware(['can:farm-produce.*']);
        Route::patch('/update/{id}', [ProductController::class, 'update'])->name('update')->middleware(['can:farm-produce.*']);
        Route::get('/delete/{id}', [ProductController::class, 'destroy'])->name('destroy')->middleware(['can:farm-produce.*']);
        Route::delete('/delete/{id}', [ProductController::class, 'delete'])->name('delete')->middleware(['can:farm-produce.*']);
        Route::get('/show/{product_slug}', [ProductController::class, 'show'])->name('show')->middleware(['can:farm-produce.view']);;
    });

    Route::prefix('categories')->namespace('Categories')->name('categories.')->group(function () {
        Route::get('/', function () {
            return view('admin.categories.index');
        })->name('index');
    });
    Route::prefix('farm-product-types')->namespace('Farm-product-types')->name('farm-product-types.')->group(function () {

        Route::get('/', [FarmProductTypeController::class, 'index'])->name('index');
        Route::get('/show/{id}', [FarmProductTypeController::class, 'show'])->name('show');

        Route::get('/create', [FarmProductTypeController::class, 'create'])->name('create');
        Route::post('/create', [FarmProductTypeController::class, 'store'])->name('store');

        Route::get('/update/{id}', [FarmProductTypeController::class, 'edit'])->name('edit');
        Route::patch('/update/{id}', [FarmProductTypeController::class, 'update'])->name('update');

        Route::get('/delete/{id}', [FarmProductTypeController::class, 'destroy'])->name('destroy');
        Route::delete('/delete/{id}', [FarmProductTypeController::class, 'delete'])->name('delete');
    });

    Route::prefix('users')->namespace('Users')->name('users.')->middleware(['can:assign'])->group(function () {
        //List User has role
        Route::get('/list-user', [AssignController::class, 'index'])->name('permission');
    });

    //PERMISSION
    Route::prefix('permissions')->namespace('Permissions')->name('permissions.')->middleware(['can:assign'])->group(function () {

        Route::get('/role', [RoleController::class, 'index'])->name('role');
        Route::get('/create-role', [RoleController::class, 'create'])->name('create-role');
        Route::post('/create-role', [RoleController::class, 'store'])->name('store-role');
        Route::get('/update-role/{id}', [RoleController::class, 'edit'])->name('edit-role');
        Route::patch('/update-role/{id}', [RoleController::class, 'update'])->name('update-role');
        Route::get('/delete-role/{id}', [RoleController::class, 'destroy'])->name('destroy-role');
        Route::delete('/delete-role/{id}', [RoleController::class, 'delete'])->name('delete-role');

        Route::get('/', [PermissionController::class, 'index'])->name('index');
        Route::get('/create-permission', [PermissionController::class, 'create'])->name('create-permission');
        Route::post('/create-permission', [PermissionController::class, 'store'])->name('store-permission');
        Route::get('/update-permission/{id}', [PermissionController::class, 'edit'])->name('edit-permission');
        Route::patch('/update-permission/{id}', [PermissionController::class, 'update'])->name('update-permission');
        Route::get('/delete-permission/{id}', [PermissionController::class, 'destroy'])->name('destroy-permission');
        Route::delete('/delete-permission/{id}', [PermissionController::class, 'delete'])->name('delete-permission');

        Route::get('/role-permission', [AssignController::class, 'rolePermission'])->name('role-permission');
        Route::get('/assign-permission/{id}', [AssignController::class, 'assignPermission'])->name('assign-permission');
        Route::patch('/assign-permission/{id}', [AssignController::class, 'insertPermission'])->name('insert-permission');
        Route::get('/assign-role/{id}', [AssignController::class, 'assignRole'])->name('assign-role');
        Route::patch('/assign-role/{id}', [AssignController::class, 'insertRole'])->name('insert-role');
    });

    Route::prefix('orders')->namespace('Orders')->name('orders.')->group(function () {
        Route::get('/', [AdminOrderController::class, 'order'])->name('index');
        Route::patch('/update-pickup/{id}', [AdminOrderController::class, 'update_pickup'])->name('update-pickup');
        Route::get('/update-delivering/{id}', [AdminOrderController::class, 'update_delivering'])->name('update-delivering');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class PostController extends Controller
{
    private  $posts;

    public function __construct(User $userModel, Post $postModel, Category $categoryModel)
    {
        $this->user = $userModel;
        $this->post = $postModel;
        $this->category = $categoryModel;
    }
    public function index()
    {
        $role = Auth::user()->getRoleNames()->first();
        if ($role == 'admin') {
            $user_id = Auth::user()->id;
            $posts = $this->post->where('is_actived', 1)->where('user_id', $user_id)->get();
        } elseif ($role == 'farmer') {
            $user_id = Auth::user()->id;

            $posts = $this->post->where('is_actived', 1)->where('user_id', $user_id)->get();
        }
        return view('admin.posts.index', compact('posts'));
    }
    public function show($id)
    {
        $postshow = $this->post->findOrFail($id);
        return view('admin.posts.show', compact('postshow'));
    }
    public function create()
    {
        $role = Auth::user()->getRoleNames()->first();
        if($role == 'admin'){
             $categories=$this->category->where('farmer_id', Null)->get();
        }

        elseif($role == 'farmer') {
            $farmer_id = Auth::user()->farmer->id;
            $categories=$this->category->where('farmer_id', $farmer_id)->get();

        }
         return view('admin.posts.store',compact('categories'));
    }
    public function store(Request $request)
    {
        $validate_data = $request->validate(
            [
                'title' => 'required',
                'description' => 'required',
                'content' => 'required',
                'post_slug' => 'required',
                'category_id' => 'required',
                'staff_id' => 'nullable',
                'user_id',
                'is_actived'=> 'nullable',
                'thumbnail' => 'required|image'
            ]
        );
        $get_image = $request->file('thumbnail');
        $path = 'image/post/';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.', $get_name_image));
        $new_image = $name_image . rand(0, 99) . '.' . $get_image->getClientOriginalExtension();
        $link = $get_image->move($path, $new_image);
        $validate_data['thumbnail'] = $link;
        $validate_data['category_id'] =  $request['category_id'];
        $validate_data['user_id'] = auth::user()->id;
        $role = Auth::user()->getRoleNames()->first();
        if ($role == 'admin' || $role == 'farmer') {
            $validate_data['is_actived'] = 1;
            $validate_data['staff_id'] = auth::user()->id;
            $validate_data['is_actived'] = 1;
        }
        $this->post->create($validate_data);
        return redirect()->route(('admin.posts.index'));
    }
    public function edit($id)
    {
        $post = $this->post->findOrFail($id);
        $role = Auth::user()->getRoleNames()->first();
        if($role == 'admin'){
             $categories=$this->category->where('farmer_id', Null)->get();
        }

        elseif($role == 'farmer') {
            $farmer_id = Auth::user()->farmer->id;
            $categories=$this->category->where('farmer_id', $farmer_id)->get();

        }
        $is_actived = $post->is_actived;
        // dd($is_actived);

        return view('admin.posts.edit', compact('post', 'categories', 'is_actived'));
    }
    public function update(Request $request, $id)
    {
        $validate_data = $request->validate([
            'title' => 'required',
            'description' => 'required',
            'content' => 'required',
            'post_slug' => 'required',
            'category_id' => 'required',
            'staff_id' => 'nullable',
            'user_id',
            'is_actived'=> 'required',
            'thumbnail'
        ]);

        $post = $this->post->findOrFail($id);
        $old_thumbnail = $post->thumbnail;
        if ($request->hasFile('thumbnail')) {
            $get_image = $request->file('thumbnail');
            $path = 'image/post/';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.', $get_name_image));
            $new_image = $name_image . rand(0, 99) . '.' . $get_image->getClientOriginalExtension();
            $link = $get_image->move($path, $new_image);
            $validate_data['thumbnail'] = $link;
        }

        $post->update($validate_data);
        return redirect()->route(('admin.posts.index'));
    }


    public function delete($id)
    {

        $post = $this->post->findOrFail($id);
        $post->delete();
        return redirect()->route(('admin.posts.index'));
    }

    public function index_unconf()
    {
        $role = Auth::user()->getRoleNames()->first();
        if($role == 'admin'){
             $posts=$this->post->where('is_actived','0')->get();
        }

        elseif($role == 'farmer') {
            $posts = $this->post->where('is_actived','0')->get();
        }
        return view('admin.posts.unconfirmed', compact('posts'));
    }
    public function accept(Request $request, $id)
    {
        $post = $this->post->findOrFail($id);
        $data['is_actived'] = 1;
        $data['staff_id'] = auth::user()->id;
        $post->update($data);
        return redirect()->route(('admin.posts.unconfirmed'));
    }
}

app/Http/Controllers/Guest/BlogController.php
<?php

namespace App\Http\Controllers\Guest;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Post;
use App\Models\User;
use App\Models\Farmer;


class BlogController extends Controller
{
    public function __construct(User $userModel, Post $postModel, Category $categoryModel, Farmer $farmerModel)
    {
        $this->users = $userModel;
        $this->posts = $postModel;
        $this->categories = $categoryModel;
        $this->farmers = $farmerModel;
    }
    public function index($id)
    {
        $user_id = $this->farmers->where('id', $id)->first()->user_id;
        $farmer_id = $this->farmers->where('id', $id)->first()->id;
        $categories = $this->categories->where('farmer_id', $id)->get();
        $posts = $this->posts->where('user_id', $user_id)->paginate(5);;
        $new_posts = $this->posts->where('user_id', $user_id)->latest()->take(4)->get();
        return view('guest.posts.index', compact('categories', 'posts', 'new_posts', 'farmer_id'));
    }
    public function categoryPost($category_slug)
    {
        $categories = $this->categories
            ->where('category_slug', $category_slug)
            ->get();
        $category_id = $this->categories->where('category_slug', $category_slug)->first()->id;
        $posts = $this->posts
            ->where('is_actived', 1)
            ->where('category_id', $category_id)
            ->paginate(5);
        $new_posts = Post::where('is_actived', 1)
            ->latest()->take(4)->get();
        return view('guest.posts.category', compact('categories', 'posts', 'new_posts'));
    }
    public function read($post_slug)
    {
        $posts = $this->posts->where('is_actived', 1)
            ->where('post_slug', $post_slug)
            ->first();
        $category_id = $posts->category_id;
        $categories = $this->categories
            ->where('id', $category_id)
            ->get();
        $new_posts = Post::where('is_actived', 1)
            ->latest()->take(4)->get();
        return view('guest.posts.post-detail', compact('posts', 'categories', 'new_posts'));
    }
}

resources/views/guest/posts/index.blade.php
<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    @include('guest.layout.head', [
    'title' => __($title ?? 'Tin tức'),
    ])
    @stack('head')
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
</head>
<style>
.main-index {
    background-color: #f5f5f5;
}

.bg-image {
    background-image: url("{{ asset('../image/banner/qc-04.png') }}");
    height: 340px;
}

.img-qc {
    padding-bottom: 5px;
    height: 170px;
}

.post-tag {
    margin-left: 15px;
    margin-right: 15px;
    margin-bottom: 30px;
}

.post-btn {
    border: 2px solid #48702f;
    background-color: #FFFFFF;
    color: #48702f;
    font-size: 18px;
    font-weight: 600;
    line-height: 35px;
    width: 150px;
}

.post-btn:hover {
    background-color: #48702f;
    color: #FFFFFF;
}

.main-post {
    padding-left: 20px;
    padding-right: 20px;
}

.blog__btn {
    float: right;
    border: 2px solid #48702f !important;
    color: #48702f !important;
    font-weight: 600 !important;
}

.blog__btn:hover {
    background-color: #48702f;
    color: #FFFFFF !important;
}

.img-blog {
    max-height: 200px !important;
}
</style>

<body>
    <!-- Header Section Begin -->
    @if (Auth::check())
    @include('guest.layout.header-top-login')
    @else
    @include('guest.layout.header-top-logout')
    @endif
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <!-- Blog Section Begin -->
    <section class="main-index">
        <div class="ml-5 mr-5">
            <div class="row pt-2 pb-5">
                <div class="col-lg-4">
                    <div class="hero__categories">
                        <img src="{{ asset('../image/banner/qc-05.png') }}" class="img-qc">
                        <img src="{{ asset('../image/banner/qc-07.jpg') }}" class="img-qc">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="hero__item bg-image">
                        <!--
                        <div class="hero__text">
                            <span class="text-white"><big>UY TÍN&ndash;CHẤT LƯỢNG&ndash;SẠCH</big></span>
                            <h2 style="color: #ABD904;">Nông Sản Việt <br />100% <b>Organic</b></h2>
                            <h5 class="text-white">Tháng kết nối, đưa Nông sản Việt đến mọi vùng miền</h5><br>
                            <a href="#shop-now" class="primary-btn">Đặt hàng ngay hôm nay!</a>
                        </div>
                        -->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="post-tag">
                    <span class="pr-5"><button class="post-btn" onclick="location.href='{{ route('guest.index') }}'">Trang chủ</button></span>
                    <span class="pr-5"><button class="post-btn" onclick="location.href='{{ route('guest.blogs.index',$farmer_id) }}'">Tất cả</button></span>
                    @foreach ($categories as $category)
                    <span class="pr-5">
                        <button class="post-btn"
                            onclick="location.href='{{route('guest.blogs.category-post',$category->category_slug)}}'">{{ $category->name }}</button>
                    </span>
                    @endforeach
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <div class="blog__sidebar">
                        <div class="blog__sidebar__search">
                            @include('guest.layout.searching-post')
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Danh mục tin tức</h4>
                            <ul>
                                <li><a href="{{ route('guest.blogs.index',$farmer_id) }}">Tất cả</a></li>
                                @foreach ($categories as $category)
                                <li><a
                                        href="{{ route('guest.blogs.category-post', $category->category_slug) }}">{{ $category->name }}</a>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                        <div class="blog__sidebar__item">
                            <h4>Tin tức mới nhất</h4>
                            <div class="blog__sidebar__recent">
                                @foreach ($new_posts as $new_post)
                                <a href="{{ route('guest.blogs.read', $new_post->post_slug) }}"
                                    class="blog__sidebar__recent__item">
                                    <div class="blog__sidebar__recent__item__pic">
                                        <img src="../../../{{$new_post->thumbnail}}" alt="" width="100">
                                    </div>
                                    <div class="blog__sidebar__recent__item__text">
                                        <h6>{{$new_post->title}}</h6>
                                        <span>{{ Carbon\Carbon::parse($new_post->created_at)->format('d-m-Y') }}</span>
                                    </div>
                                </a>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
                @if (!empty($posts))
                <div class="col-lg-9 col-md-8 shadow">
                    @foreach ($posts as $post)
                    <div class="row main-post">
                        <table class="blog__item">
                            <div class="form-group col-md-5">
                                <div class="blog__item__pic">
                                    <img src="../../../{{$post->thumbnail}}" alt="{{$post->title}}" class="img-blog">
                                </div>
                            </div>
                            <div class="form-group col-md-7">
                                <div class="blog__item__text">
                                    <ul>
                                        <li><i
                                                class="fa-solid fa-calendar"></i>&ensp;{{ Carbon\Carbon::parse($post->created_at)->format('d-m-Y') }}
                                        </li>                                   
                                    </ul>
                                    <h5><a href="{{route('guest.blogs.read',$post->post_slug)}}">{{$post->title}}</a>
                                    </h5>
                                    <p>{{$post->description}}</p>
                                    <a href="{{route('guest.blogs.read',$post->post_slug)}}" class="blog__btn">Tìm
                                        hiểu
                                        thêm
                                        <span class="arrow_right"></span></a>
                                </div>
                            </div>
                        </table>
                    </div>
                    @endforeach
                    <br>
                    <div class="col-lg-12 pb-2">
                       {{$posts->links()}}
                    </div>
                </div>
                @else
                <h5>Không có bài viết</h5>
                @endif
            </div>
        </div>
    </section>
    <!-- Blog Section End -->

    <!-- Footer Section Begin -->
    @include('guest.layout.footer')
    <!-- Footer Section End -->
    @include('guest.layout.script')
</body>

</html>